name: 'Feature Request & Ideas 🚀'
description: Suggest a new feature or improvement (this does not mean you have to implement it)
title: 'Feature: '
labels:
  - feature
  - backlog
  - enhancement
assignees: 'tulpy'

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report! Before submitting, please make sure to [search through existing issues](https://github.com/Insight-Services-APAC/azure-landing-zones-vending-machine/issues).

  - type: textarea
    id: feature_description
    attributes:
      label: Feature or Idea - What?
      placeholder: Briefly describe what the new feature, idea or enhancement entails.
    validations:
      required: true

  - type: textarea
    id: feature_reason
    attributes:
      label: Feature or Idea - Why?
      placeholder: Briefly describe why the new feature, idea or enhancement is required and what outcome you are trying to achieve.
    validations:
      required: true

  - type: markdown
    attributes:
      value: 'Thanks for completing this form!'
